### ISSUE TITLE
[BUG] The best pth you provided cannot be loaded into the model.

### ISSUE THREAD

**Issue by littleJu1y** [QiShanZhang/SLSforASVspoof-2021-DF#1]
The best pth you provided cannot be loaded into the model. The weight size of the model I obtained using your training method is 1.27g, while your best pth is 1.18g

**Comment by QiShanZhang** [comment]
I will check that problem, resolution will comming soon. what performence is yourself trained model?

**Comment by QiShanZhang** [comment]
you can try use that baiduwangpan link https://pan.baidu.com/s/1dj-hjvf3fFPIYdtHWqtCmg?pwd=shan 
提取码：shan 
the google drive link will be updata after uploding successful

**Comment by QiShanZhang** [comment]
thanks for you question

**Comment by QiShanZhang** [comment]
The google drive link have been updataed.

**Comment by littleJu1y** [comment]
Thank you for your sincere reply, I will try again. Thank you again.

**Comment by QiShanZhang** [comment]
ok. please feel free if you have another question.
