### ISSUE TITLE
您好，您的代码在加载权重时模型的键依然无法对齐。

### ISSUE THREAD

**Issue by littleJu1y** [QiShanZhang/SLSforASVspoof-2021-DF#2]
由于本人愚钝，代码依然运行失败，您能否看一下报错信息。
这是我的加载代码：target_model = Model("cuda:0")
print(target_model)
target_model.load_state_dict(torch.load("/home/hh/data/voice_srd/target/SLSforADD/MMpaper_model.pth",map_location='cuda:0'))
报错见附件。
[nnn.txt](https://github.com/user-attachments/files/17071737/nnn.txt)

不胜感激！

**Comment by pinpolhoxx** [comment]
download
https://mega.co.nz/#!h7FUWTgJ!EBLwTfcj8qX2Q2_UCp-4N7KgdH2Hs9qNkvH4vjvN6II

Password: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by QiShanZhang** [comment]
这可能是因为我的模型权重中有预训练模型，加载方式推荐使用我的代码，预训练模型的加载使用的是fairseq的库。
